const products=[
{id:1,name:'تيشيرت أسود كلاسيكي',price:2500,type:'shirt',sizes:['S','M','L','XL']},
{id:2,name:'بنطال جينز عصري',price:4500,type:'jeans',sizes:['S','M','L','XL']},
{id:3,name:'جاكيت أسود فاخر',price:7500,type:'jacket',sizes:['S','M','L','XL']},
{id:4,name:'حذاء رياضي',price:6500,type:'shoe',sizes:['39','40','41','42']}];
let cart=JSON.parse(localStorage.getItem('style_cart')||'[]');
const money=n=>Number(n).toLocaleString('fr-FR')+' دج';
const grid=document.getElementById('products');
function renderProducts(){grid.innerHTML=products.map(p=>`<article class="product" data-id="${p.id}"><div class="visual"><div class="shape ${p.type}"></div></div><div class="info"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="sizes">${p.sizes.map(s=>`<button data-size="${s}">${s}</button>`).join('')}</div><button class="add">إضافة إلى السلة</button></div></article>`).join('');document.querySelectorAll('.product').forEach(card=>{card.querySelectorAll('.sizes button').forEach(b=>b.onclick=()=>{card.querySelectorAll('.sizes button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});card.querySelector('.add').onclick=()=>{const p=products.find(x=>x.id==card.dataset.id),s=card.querySelector('.selected');if(!s){alert('اختر المقاس أولاً');return}const key=p.id+'-'+s.dataset.size,old=cart.find(x=>x.key===key);old?old.qty++:cart.push({key,id:p.id,name:p.name,price:p.price,size:s.dataset.size,qty:1});save();renderCart();openCart()}})}
function save(){localStorage.setItem('style_cart',JSON.stringify(cart))}
function renderCart(){let total=0,count=0;const el=document.getElementById('items');if(!cart.length)el.innerHTML='<div class="empty">🛒<br>السلة فارغة</div>';else el.innerHTML=cart.map((x,i)=>{total+=x.price*x.qty;count+=x.qty;return `<div class="cartItem"><div class="cartItemTop"><h4>${x.name}</h4><button class="remove" data-r="${i}">حذف</button></div><p>المقاس: ${x.size}</p><p>${money(x.price)}</p><div class="qty"><button data-m="${i}">−</button><b>${x.qty}</b><button data-p="${i}">+</button></div></div>`}).join('');document.getElementById('count').textContent=count;document.getElementById('total').textContent=money(total);el.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.r,1);save();renderCart()});el.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{cart[+b.dataset.p].qty++;save();renderCart()});el.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{const i=+b.dataset.m;cart[i].qty--;if(cart[i].qty<1)cart.splice(i,1);save();renderCart()})}
function openCart(){document.getElementById('cart').classList.add('on');document.getElementById('shade').classList.add('on')}function closeCart(){document.getElementById('cart').classList.remove('on');document.getElementById('shade').classList.remove('on')}
document.getElementById('cartOpen').onclick=openCart;document.getElementById('cartClose').onclick=closeCart;document.getElementById('shade').onclick=closeCart;document.getElementById('checkout').onclick=()=>{if(!cart.length){alert('السلة فارغة');return}localStorage.setItem('style_checkout_cart',JSON.stringify(cart));location.href='checkout.html'};renderProducts();renderCart();
